### ISSUE TITLE
Avancement

### ISSUE THREAD

**Issue by ealbert-42** [ealbert-42/Fillit#3]
.

**Comment by simonhillfr** [comment]
je crois qu'on reçoit plus les notifs d'une conversation apres un merge..
tu bosse sur quoi du coup la ?

**Comment by ealbert-42** [comment]
J'viens de refaire le TODO_LIST, j'regarde ton algo pour voir si on peut y intégrer un map_limit puis j'essaie de faire un main potable

**Comment by simonhillfr** [comment]
ok fait un merge request si ta des trucs a mettre a jour

**Comment by simonhillfr** [comment]
integrer un map limit sur l'algo? c'est a dire ?
il y est deja non ?

ta changé quoi sur le main ?

**Comment by simonhillfr** [comment]
oublie pas que j'ai bossé sur le main hier..

**Comment by ealbert-42** [comment]
Bon, sur le main j'ai fait en sorte de stocker la map dans une structure, du coup j'ai dû changer le generate_map aussi, mais au final on a une structure qui est bien malloc, et qui est utilisable
Le main a le même squelette cela dit, le seul truc que j'ai rajouté c'est de close fd après le read, parce qu'on en a plus besoin

**Comment by ealbert-42** [comment]
Par contre y'a un truc qui m'échappe, sur "algo.c" t'as une structure s_map, tu peux m'expliquer pour chaque variable ce à quoi ça correspond ?

**Comment by simonhillfr** [comment]
Yep:

**maxsize** : taille maxi de la map (ex: 6 pour une map de 6*6)

**maxposition** : peut etre pas besoin d'etre une variable, car on peut la chopper par calcul. la valeur est de 15 pour une map de 4*4. C'est le nombre total de cases. La premiere valant 0

**position** : a priori je lai pas utilisée, ou en tout cas elle peut etre remplacée par une variable dans la fonction algo puisque elle est remise a zero a chaque fois.

**Comment by ealbert-42** [comment]
Ok je vais changer le generate-map alors

**Comment by simonhillfr** [comment]
ah oui pour le stocker dans la structure ? ok.

**Comment by simonhillfr** [comment]
bon du coup je suis plus a jour, fait une pull request quand tes au bout de qqchose pour me tenir au courant, la je vois pas trop sur quoi bosser

**Comment by ealbert-42** [comment]
Bah pour l'instant ce qui est fait :
On enregistre les tetriminos dans une structure
On enregistre la map dans une structure

J'ai pas encore testé l'algo par contre, et je pense qu'il ne reste que ça

**Comment by simonhillfr** [comment]
il va rester le **makefile**
et aussi un beau fichier de test simple

**Comment by ealbert-42** [comment]
Ouaip
J'm'occupe du Makefile

**Comment by simonhillfr** [comment]
ok. bon bah je vais bouffer alors, j'attends ton pull request.

**Comment by ealbert-42** [comment]
Je modifie direct sur git, donc tout est déjà push

**Comment by simonhillfr** [comment]
ah ok. Bon bah tu me dira quand ta finis.
Je viens de penser a un truc majeur! avec ce sytème de position de case que l'on traduit ensuite en coordonnées, c'est hyper pratique mais ça ne marche plus si la map fait deja 12 en taille, et si je me souviens bien, c'est la solution qu'on avait adopté. Il va donc falloir faire une fonction qui génère une nouvelle map de taille incrémentée.

**Comment by ealbert-42** [comment]
Mais non t'inquiètes !

En gros, on va faire une condition du genre :

Si map[position à comparer] est un "." et que position < map_limit

Alors on peut le placer

Et si on a testé toutes les solutions, il suffit de faire map_limit + 1

**Comment by simonhillfr** [comment]
ah oui ok puisque fait % map->maxsize !

**Comment by simonhillfr** [comment]
Quelles sont les nouvelles ? T'en est où ? T'a besoin d'aide sur quelquechose?

**Comment by ealbert-42** [comment]
Bah j'étais en train de revérifier mais j'crois qu'on a plus qu'à faire un main pour tester tout ça :p
Demain j'viens et je ferais des tests

**Comment by simonhillfr** [comment]
ya pas de main encore ?

**Comment by simonhillfr** [comment]
enfin j'en avais fait un, il était pas complet ?

**Comment by ealbert-42** [comment]
Je l'ai juste modifié un peu, le squelette est le même si tu regardes bien

**Comment by simonhillfr** [comment]
ok, super, on voit ça demain alors ? J'ai un peu perdu le fil de ce que tu as fait, donc si il reste des trucs à faire selon toi dit moi. Sinon on peut limite tester dès ce soir ?

**Comment by ealbert-42** [comment]
Ouais on pourrait mais je pense que ce serait mieux qu'on voit ça demain tous les deux

Sinon j'vois rien à refaire pour l'instant

**Comment by simonhillfr** [comment]
ok, tout est merge dans master alors ?
Demain je pars a 14h donc on peut se capter le matin.

**Comment by ealbert-42** [comment]
Ok bah j'essaie de me coucher tôt aujourd'hui

Normalement tout est bon sauf si t'as fait une pull request en dehors du test

**Comment by simonhillfr** [comment]
Non, rien a ajouter de mon coté.
A demain alors !
De bonne heure et de bonne humeur ! :D

**Comment by ealbert-42** [comment]
Espérons ! xD
