### ISSUE TITLE
constipation: probleme de push!

### ISSUE THREAD

**Issue by simonhillfr** [ealbert-42/Fillit#7]
Bon je viens de peter les ploms sur cette histoire de push pour lequel je navais pas les droits sur mon propre rep! Du coup j'ai push sans fair expres direct sur la branche master de ton rep.
Voila les MAJ : 

gros menage sur les fichiers, rajout de static devant les fonctions locales, netoyage de plein de caca de debug sur ft_trim_tetri, creation de read_file.c au lieu de reading.c avant, creation du main.

Rien d'essentiel en vrai mais rien que ces histoires de git viennent de me faire perdre une heure et je comprends toujours pas pkoi je nai plus les droits sur mes rep, mais que jarrive a push sur le tiens !

**Comment by simonhillfr** [comment]
Si tu clique sur "menage de printemp" (le nom du commit) tu verra les changements. Je trouve que la vue SPLIT est plus parlante (a droite en haut)

**Comment by ealbert-42** [comment]
Perso j'ai push le save_tetri sur tmp
Mais j'vois pas comment t'aurais plus accès à tes repositories en fait, c'est assez chelou

**Comment by simonhillfr** [comment]
ouais c’est moi en local d’ou viens l’erreur je crois.
Mis je me suis demerdé je t’ai fait une demande de merge je sais pas si ta vu ?
